---
title: "GLMM Alternative Simulation-based dispersion test: Approximation of Pearson residuals"
author: ""
date: "`r Sys.Date()`"
output: 
  rmdformats::readthedown:
    highlight: kate
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: false
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=F)

library(DHARMa)
library(here)
library(tidyverse)
library(cowplot); library(patchwork)
theme_set(theme_cowplot() + 
            theme(panel.background = element_rect(color = "black")))

# plot Colors
source(here("functions_others", "plotColors.R"))
```

# Simulated data

```{r}
load(here("data", "7_glmmBin_alternative_power.Rdata")) # simulated data

#time spent + stupid way to convert mins to hours for some times
tspent <- map_dbl(out.binA, "time")
stime <- map(out.binA, "time")
#tspent[map(stime, attr, "units") == "mins"] <- tspent[map(stime, attr, "units") 
 #                                                     == "mins"]/60
summary(tspent) # secs

simuls.binA <- map_dfr(out.binA, "simulations", .id="model") %>%
  separate(model, c("ngroups", "sampleSize", "intercept"), sep="_") %>%
  rename("overdispersion" = "controlValues")
```

```{r}
load(here("data", "7_glmmPois_alternative_power.Rdata")) # simulated data

#time spent + stupid way to convert mins to hours for some times
tspent <- map_dbl(out.poisA, "time")
stime <- map(out.poisA, "time")
#tspent[map(stime, attr, "units") == "mins"] <- tspent[map(stime, attr, "units") 
#                                                     == "mins"]/60
summary(tspent) # 1

#simulations
simuls.poisA <- map_dfr(out.poisA, "simulations", .id="model") %>%
  separate(model, c("ngroups", "sampleSize", "intercept"), sep="_") %>%
  rename("overdispersion" = "controlValues") 
```

# Percentage of zeros 

Looking at the percentage of zeros in the simulations

```{r}
simuls.poisA %>%
  mutate(sampleSize = fct_relevel(sampleSize,  "200","500","1000"))%>%
  ggplot(aes(x=as.factor(overdispersion), y=prop.zero, col=as.factor(sampleSize))) +
  geom_boxplot() +
  facet_grid(sampleSize~intercept, scales="free") +
  labs(title="Poisson: Prop obs with zero SD simulated data") +
  theme(panel.background = element_rect(color="black"))
```

```{r}
zerop <- simuls.poisA %>% filter(prop.zero >0)
table(zerop$sampleSize, zerop$intercept)
```

The percentage of simulations with one zero SD `r dim(zerop)[1]*100/dim(simuls.poisA)[1] `

No zeros for binomial
```{r}
simuls.binA %>%
  mutate(sampleSize = fct_relevel(sampleSize,  "200","500","1000")) %>%
  ggplot(aes(x=as.factor(overdispersion), y=prop.zero, col=as.factor(sampleSize))) +
  geom_boxplot() +
  facet_grid(sampleSize~intercept, scales="free") +
  labs(title="Binomial: Prop obs with zero SD simulated data") +
  theme(panel.background = element_rect(color="black"))
```

**All following results without zeros**

```{r}
simuls.poisA0 <- simuls.poisA %>% filter(prop.zero == 0)
```


# Power

Combining with other results

```{r}
p.binA <- simuls.binA %>% 
  group_by(sampleSize, ngroups, intercept, overdispersion) %>%
  summarise(p.sig = sum(Alt.p<0.05,na.rm=T),
            nsim = length(Alt.p[!is.na(Alt.p)]))
p.binA$prop.sig <- p.binA$p.sig/p.binA$nsim
p.binA$intercept <- fct_relevel(p.binA$intercept, "-1.5", "0", "1.5")
#p.binA$ngroups <- fct_relevel(p.binA$ngroups, "10", "50", "100")
p.binA$sampleSize <- as.factor(as.numeric(p.binA$sampleSize))

load(here("data", "5_glmmBin_power.Rdata")) # simulated data
#simulations
simuls.bin <- map_dfr(out.bin, "simulations", .id="model") %>%
  separate(model, c("ngroups", "sampleSize", "intercept"), sep="_") %>%
  rename("overdispersion" = "controlValues")

# power
p.bin <- simuls.bin %>% dplyr::select(Pear.p.val, dhaUN.p.val, dhaCO.p.val,
                                       refCO.p.val, replicate,
                                      ngroups,
                                      overdispersion, intercept, sampleSize) %>%
  pivot_longer(1:5, names_to = "test", values_to = "p.val") %>%
  group_by(sampleSize, ngroups, intercept, overdispersion, test) %>%
  summarise(p.sig = sum(p.val<0.05,na.rm=T),
            nsim = length(p.val[!is.na(p.val)]))
p.bin$prop.sig <- p.bin$p.sig/p.bin$nsim
p.bin$intercept <- fct_relevel(p.bin$intercept, "-3", "-1.5", "0", "1.5", "3")
p.bin$ngroups <- fct_relevel(p.bin$ngroups, "10", "50", "100")
p.bin$sampleSize <- as.factor(as.numeric(p.bin$sampleSize))

bindata <- bind_rows(list(p.binA %>% mutate(test = "approxPear"),
                     p.bin)) 
```

```{r, fig.height=8}
bindata %>% filter(ngroups==100, intercept %in% c("-1.5", "0", "1.5"),
                   !test %in% c("refCO.p.val", "Pear.p.val"),  
                   sampleSize != 10000) %>%
  ggplot(aes(x=overdispersion, y=prop.sig, col=test))+
  geom_point(alpha=0.7) + geom_line(alpha=0.7) +
  scale_color_discrete(labels=c("Approximate Pearson",  
                                "conditional sim-based variance",
                                "unconditional sim-based variance",
                                "nonparam. Pearson residuals"))+
  facet_grid(sampleSize~intercept) +
  geom_hline(yintercept = 0.5, linetype="dotted") +
  ylab("Power") + xlab("Overdispersion")+
  ggtitle("Binomial", subtitle = "Ntrials=10") +
  theme(panel.background = element_rect(color="black"),
        legend.position = "bottom") + 
  guides(color=guide_legend(nrow=2, byrow=TRUE))
ggsave(here('figures', '7_approxPearson_bin_powerGLMM.jpeg'), height=10, width=10)
```


```{r}
p.poisA <- simuls.poisA0 %>% 
  group_by(sampleSize, ngroups, intercept, overdispersion) %>%
  summarise(p.sig = sum(Alt.p<0.05,na.rm=T),
            nsim = length(Alt.p[!is.na(Alt.p)]))
p.poisA$prop.sig <- p.poisA$p.sig/p.poisA$nsim
p.poisA$intercept <- fct_relevel(p.poisA$intercept, "-1.5", "0", "1.5")
p.poisA$ngroups <- fct_relevel(p.poisA$ngroups, "10", "50", "100")
p.poisA$sampleSize <- as.factor(as.numeric(p.poisA$sampleSize))

load(here("data", "5_glmmPois_power.Rdata")) # simulated data
simuls.pois <- map_dfr(out.pois, "simulations", .id="model") %>%
  separate(model, c("ngroups", "sampleSize", "intercept"), sep="_") %>%
  rename("overdispersion" = "controlValues")

p.pois <- simuls.pois %>% dplyr::select(Pear.p.val, dhaUN.p.val, dhaCO.p.val,
                                        refCO.p.val, replicate,
                                        ngroups,
                                        overdispersion, intercept, sampleSize) %>%
  pivot_longer(1:5, names_to = "test", values_to = "p.val") %>%
  group_by(sampleSize, ngroups, intercept, overdispersion, test) %>%
  summarise(p.sig = sum(p.val<0.05,na.rm=T),
            nsim = length(p.val[!is.na(p.val)]))
p.pois$prop.sig <- p.pois$p.sig/p.pois$nsim
p.pois$intercept <- fct_relevel(p.pois$intercept, "-3", "-1.5", "0", "1.5", "3")
p.pois$ngroups <- fct_relevel(p.pois$ngroups, "10", "50", "100")
p.pois$sampleSize <- as.factor(as.numeric(p.pois$sampleSize))

poisdata <- bind_rows(list(p.poisA %>% mutate(test = "approxPear"),
                          p.pois)) 
```

```{r, fig.height=8}
poisdata %>% filter(ngroups==100, intercept %in% c("-1.5", "0", "1.5"),
                    !test %in% c("refCO.p.val", "Pear.p.val"), 
                   sampleSize != 10000) %>%
  ggplot(aes(x=overdispersion, y=prop.sig, col=test))+
  geom_point(alpha=0.7) + geom_line(alpha=0.7) +
  scale_color_discrete(labels=c("Approximate Pearson",  
                                "conditional sim-based variance",
                                "unconditional sim-based variance",
                                "nonparam. Pearson residuals"))+
  facet_grid(sampleSize~intercept) +
  geom_hline(yintercept = 0.5, linetype="dotted") +
    ylab("Power") + xlab("Overdispersion")+
  ggtitle("Poisson") +
  theme(panel.background = element_rect(color="black"),
        legend.position = "bottom") + 
  guides(color=guide_legend(nrow=2, byrow=TRUE))
ggsave(here('figures', '7_approxPearson_pois_powerGLMM.jpeg'), height=10, width=10)
```

